### ISSUE TITLE
Can't download curseforge mods

### ISSUE THREAD

**Issue by HHonzik** [RandomGgames/RMMUD#4]
I can't download curseforge mods, i do have my curseforge api key in the file and i also uploaded latest.log from it
i am using a buch of mods but the last 2 mods are only on curseforge and it didn't work.
[latest.log](https://github.com/RandomGgames/RMMUD/files/11396846/latest.log)

**Comment by HHonzik** [comment]
`Enabled: true
Loader: Fabric
Version: 1.19.4
Directory: H:\Data\Minecraft mod instalator\Updatemods\
Mods:
  - https://modrinth.com/mod/fabric-api
  - https://modrinth.com/mod/sodium
  - https://modrinth.com/mod/indium
  - https://modrinth.com/mod/carpet
  - https://modrinth.com/mod/modmenu
  - https://modrinth.com/mod/betterf3
  - https://modrinth.com/mod/ad-astra
  - https://modrinth.com/mod/resourceful-lib
  - https://modrinth.com/mod/resourceful-config
  - https://modrinth.com/mod/botarium
  - https://modrinth.com/mod/distanthorizons
  - https://modrinth.com/mod/lambdynamiclights
  - https://modrinth.com/mod/fastload
  - https://modrinth.com/mod/architectury-api
  - https://modrinth.com/mod/bits-and-chisels
  - https://modrinth.com/mod/pehkui
  - https://modrinth.com/mod/rei
  - https://modrinth.com/mod/immersiveportals
  - https://modrinth.com/plugin/simple-voice-chat
  - https://modrinth.com/mod/vivecraft
  - https://curseforge.com/minecraft/mc-mods/identity
  - https://curseforge.com/minecraft/mc-mods/worldedit`

**Comment by RandomGgames** [comment]
It seems to have worked fine for me using v3.6.0. Double check you put your CurseForge API key in correctly, and that it is still valid. The `RMMUDConfig.yaml` file should look something like this:
```yaml
# Your CurseForge API key goes here.
# Only required if using CurseForge links.
# To get an API key: Go to https://console.curseforge.com/?#/api-keys, sign in, click API keys on the left, and copy paste the key here
CurseForge API Key: $7bs1565.jshdbfkawbf/kshdbfgas.khsebfklasnfklasngf
```
(Note, the API key shown above does not actually exist, I just typed random letters. Never share your API key!)

Let me know if that fixes it.

**Comment by HHonzik** [comment]
It gives me three $ and no /, and still i can't download curseforge mods

**Comment by RandomGgames** [comment]
I can't think of anything other than it being a weird curseforge issue and not my script, specially since your instance is working fine for me.

Maybe try regenerating your CurseForge API key and putting it into your `RMMUDConfig.yaml` file?
![image](https://user-images.githubusercontent.com/17207260/236676399-30a74406-c7bd-46e0-8c30-818d2e519a23.png)

**Comment by HHonzik** [comment]
I tryed regenerating it like idk 10-20 times and still the same issue.

**Comment by RandomGgames** [comment]
Try turning on debug logging by editing RMMUD.py with a text editor. `logging_level = logging.INFO`, change it to `logging_level = logging.DEBUG`. Should be line 16. Upload your log again after changing that.

**Comment by HHonzik** [comment]
Here is my log:

[latest.log](https://github.com/RandomGgames/RMMUD/files/11415526/latest.log)

**Comment by RandomGgames** [comment]
Ah now CurseForge links are no longer working on my end too, even though it was working fine when I tested yours and have used instances that worked before. Now suddenly for me too.

It must be due to the CurseForge updating their systems or things are not functioning properly at the moment or the API has changed and the current code doesn't work. I can look into it more in the coming days, but for now, if I'm correct and it's due to changes on CurseForge's side of things, they won't work at all until I release an update.

Look out for v3.6.1 in releases in the coming week(s).

**Comment by RandomGgames** [comment]
Try with v3.6.1
https://github.com/RandomGgames/RMMUD/blob/main/RMMUD.py

**Comment by HHonzik** [comment]
Now it's working.
